import {topics,paths} from './content.js';
const FIREBASE_VERSION='12.16.0';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={user:null,firebase:null};
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nav(n){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${n}View`)?.classList.add('active');$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===n));window.scrollTo({top:0,behavior:'smooth'})}
function initTheme(){if(store.get('theme','dark')==='light')document.documentElement.classList.add('light')}
function renderTopics(){$('#topicSelect').innerHTML=topics.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}
function chooseTopic(){if($('#modeSelect').value==='random')return topics[Math.floor(Math.random()*topics.length)];return topics.find(t=>t.id===$('#topicSelect').value)||topics[0]}
function renderStudy(t){const n=Number($('#chapterCount').value);const refs=[...t.chapters,...t.links].slice(0,n);$('#studyResult').innerHTML=`<article class="study-output section-block"><div class="section-heading"><div><p class="eyebrow">${esc($('#translationSelect').value)}</p><h2>${esc(t.name)}</h2></div><button id="studySpeakBtn" class="secondary">▶ Poslušaj vse</button></div><p><b>${esc(t.verse)}</b> — ${esc(t.quote)}</p><h4>Izbrana poglavja</h4><p>${refs.map(esc).join(' · ')}</p><h4>Povzetek</h4><p>${esc(t.summary)}</p><h4>Kontekst</h4><p>${esc(t.context)}</p><h4>Pomen za nas danes</h4><p>${esc(t.today)}</p><h4>Vprašanja za razmislek</h4><ol>${t.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><div class="hero-actions"><button class="primary" id="studyToJournal">Zapiši svoje razmišljanje</button></div></article>`;$('#studyResult').scrollIntoView({behavior:'smooth'})}
function getVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>v.lang?.toLowerCase().startsWith('sl'))||vs.find(v=>v.lang?.toLowerCase().startsWith('hr'))||null}
function speak(text){if(!('speechSynthesis'in window)){toast('Naprava ne podpira zvočnega branja.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='sl-SI';u.voice=getVoice();u.rate=.92;u.onstart=()=>toast('Predvajanje se je začelo.');u.onerror=()=>toast('Predvajanje ni uspelo. Preveri slovenski glas v sistemu.');speechSynthesis.speak(u)}
function stopSpeak(){if('speechSynthesis'in window)speechSynthesis.cancel()}
speechSynthesis?.getVoices(); if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices();

function renderKeywordResults(query=''){const q=query.trim().toLowerCase();if(!q){$('#keywordResults').innerHTML='';return}const found=topics.filter(t=>[t.name,...t.keywords,t.summary,t.today].join(' ').toLowerCase().includes(q));$('#keywordResults').innerHTML=found.length?found.map(t=>`<article class="list-card keyword-result"><div><b>${esc(t.verse)} · ${esc(t.name)}</b><p>${esc(t.quote)}</p></div><button class="text-btn use-keyword" data-topic="${t.id}">Odpri →</button></article>`).join(''):`<p class="empty-state">Za »${esc(query)}« ni pripravljenega zadetka. Poskusi: vera, mir, upanje, ljubezen ali odpuščanje.</p>`}
function pathState(){return store.get('pathProgress',{})}
function renderPaths(){const progress=pathState();$('#pathsList').innerHTML=paths.map(p=>{const done=Math.min(progress[p.id]||0,p.days.length),pct=Math.round(done/p.days.length*100),next=p.days[done]||'Pot zaključena';return `<article class="list-card"><div class="section-heading"><div><h3>${esc(p.title)}</h3><p class="muted">${esc(p.desc)}</p></div><span class="pill">${done}/${p.days.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><p><b>${done<p.days.length?'Naslednje branje':'Zaključeno'}:</b> ${esc(next)}</p><button class="primary path-step" data-path="${p.id}">${done?'Označi naslednji dan':'Začni pot'}</button><button class="text-btn path-reset" data-path="${p.id}">Ponastavi</button></article>`}).join('');renderContinue()}
function renderContinue(){const progress=pathState();const active=store.get('activePath',null);const p=paths.find(x=>x.id===active);if(!p){$('#continuePill').textContent='Ni začete poti';$('#continueTitle').textContent='Izberi bralno pot';$('#continueText').textContent='Začni v razdelku Moje poti.';$('#continueProgress').style.width='0%';return}const done=Math.min(progress[p.id]||0,p.days.length),pct=Math.round(done/p.days.length*100);$('#continuePill').textContent=`${done}. dan od ${p.days.length}`;$('#continueTitle').textContent=p.title;$('#continueText').textContent=done<p.days.length?`Naslednje: ${p.days[done]}`:'Pot je zaključena.';$('#continueProgress').style.width=`${pct}%`}
function renderJournal(){const a=store.get('journal',[]);$('#journalEntries').innerHTML=a.length?a.map((e,i)=>`<article class="list-card"><div class="section-heading"><div><h3>${esc(e.title)}</h3><p class="muted">${new Date(e.date).toLocaleString('sl-SI')}</p></div><button class="icon-btn delete-journal" data-i="${i}">×</button></div><p>${esc(e.text).replace(/\n/g,'<br>')}</p>${e.prayer?`<p><b>Moja molitev:</b><br>${esc(e.prayer).replace(/\n/g,'<br>')}</p>`:''}</article>`).join(''):'<p class="empty-state">Še nimaš shranjenih zapisov.</p>'}
function saveJournal(){const e={title:$('#journalTitle').value.trim()||'Moje razmišljanje',text:$('#journalText').value.trim(),prayer:$('#prayerText').value.trim(),date:new Date().toISOString()};if(!e.text&&!e.prayer){toast('Vnesi zapis ali molitev.');return}const a=store.get('journal',[]);a.unshift(e);store.set('journal',a);renderJournal();$('#journalTitle').value=$('#journalText').value=$('#prayerText').value='';syncUserData();toast('Zapis je shranjen.')}
function renderGroups(){$('#groupsList').innerHTML='<p class="empty-state">Prijavi se z Googlom za sinhronizirane skupine.</p>'}
function setSync(s){$('#syncStatus').textContent=s;$('#lastSync').textContent=new Date().toLocaleString('sl-SI')}
async function loadFirebase(){const c=window.MOJABESEDA_FIREBASE_CONFIG;if(!c?.apiKey){setSync('Lokalno');return}try{const [a,au,d]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const app=a.initializeApp(c),auth=au.getAuth(app),db=d.getFirestore(app);state.firebase={auth,db,...au,...d};await au.getRedirectResult(auth).catch(()=>null);au.onAuthStateChanged(auth,onAuth);setSync('Firebase pripravljen')}catch(e){console.error(e);setSync('Napaka povezave')}}
async function googleLogin(){if(!state.firebase){toast('Firebase povezava ni pripravljena.');return}const {auth,GoogleAuthProvider,signInWithPopup,signInWithRedirect}=state.firebase;const p=new GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});try{await signInWithPopup(auth,p)}catch(e){if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(e.code))await signInWithRedirect(auth,p);else{console.error(e);toast(`Prijava ni uspela: ${e.code||'neznana napaka'}`)}}}
async function onAuth(u){state.user=u;$('#googleLoginBtn').classList.toggle('hidden',!!u);$('#logoutBtn').classList.toggle('hidden',!u);$('#profileName').textContent=u?.displayName||'Gostujoči uporabnik';$('#profileEmail').textContent=u?.email||'Lokalni način';$('#profileBtn').textContent=u?(u.displayName||'MB').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase():'DG';$('#accountStatus').textContent=u?'Prijavljen':'Neprijavljen';if(u){await syncUserData();await loadUserData();setSync('Sinhronizirano')}else setSync('Lokalno')}
async function syncUserData(){if(!state.user||!state.firebase)return;const {db,doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(db,'users',state.user.uid),{uid:state.user.uid,email:state.user.email||'',displayName:state.user.displayName||'',pathProgress:pathState(),activePath:store.get('activePath',null),journal:store.get('journal',[]),updatedAt:serverTimestamp()},{merge:true})}
async function loadUserData(){if(!state.user||!state.firebase)return;const {db,doc,getDoc}=state.firebase;const s=await getDoc(doc(db,'users',state.user.uid));if(s.exists()){const d=s.data();if(d.pathProgress)store.set('pathProgress',d.pathProgress);if(d.activePath)store.set('activePath',d.activePath);if(Array.isArray(d.journal))store.set('journal',d.journal);renderPaths();renderJournal()}}
function bind(){document.addEventListener('click',async e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav);if(e.target.closest('#profileBtn'))nav('profile');if(e.target.closest('#dailySpeakBtn'))speak(`${$('#dailyTitle').textContent}. ${$('#dailyVerse').textContent}. ${$('#dailyReference').textContent}`);if(e.target.closest('#dailyStopBtn'))stopSpeak();if(e.target.closest('#studySpeakBtn'))speak($('#studyResult').innerText);if(e.target.closest('#studyToJournal')){nav('journal');$('#journalTitle').value=`Razmišljanje: ${$('#studyResult h2')?.textContent||''}`};const k=e.target.closest('.use-keyword');if(k){const t=topics.find(x=>x.id===k.dataset.topic);$('#topicSelect').value=t.id;nav('study');renderStudy(t)}const ps=e.target.closest('.path-step');if(ps){const p=paths.find(x=>x.id===ps.dataset.path),pr=pathState();pr[p.id]=Math.min((pr[p.id]||0)+1,p.days.length);store.set('pathProgress',pr);store.set('activePath',p.id);renderPaths();await syncUserData();toast('Napredek poti je shranjen.')}const pr=e.target.closest('.path-reset');if(pr){const x=pathState();x[pr.dataset.path]=0;store.set('pathProgress',x);renderPaths();await syncUserData()}const dj=e.target.closest('.delete-journal');if(dj){const a=store.get('journal',[]);a.splice(Number(dj.dataset.i),1);store.set('journal',a);renderJournal();await syncUserData()}});$('#themeToggle').onclick=()=>{document.documentElement.classList.toggle('light');store.set('theme',document.documentElement.classList.contains('light')?'light':'dark')};$('#chapterCount').oninput=e=>$('#chapterCountValue').textContent=e.target.value;$('#studyForm').onsubmit=e=>{e.preventDefault();renderStudy(chooseTopic())};$('#keywordSearchBtn').onclick=()=>renderKeywordResults($('#keywordSearch').value);$('#keywordSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();renderKeywordResults(e.target.value)}};$('#saveJournalBtn').onclick=saveJournal;$('#googleLoginBtn').onclick=googleLogin;$('#logoutBtn').onclick=()=>state.firebase?.signOut(state.firebase.auth);$('#addGroupBtn').onclick=()=>$('#groupDialog').showModal();$('#createGroupConfirm').onclick=e=>{e.preventDefault();toast('Skupine bodo na voljo po prijavi in potrjeni Firestore povezavi.');$('#groupDialog').close()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);
initTheme();renderTopics();renderPaths();renderJournal();renderGroups();bind();loadFirebase();