export const topics=[
{id:'love',name:'Ljubezen',keywords:['ljubezen','odpuščanje','služenje'],chapters:['1 Korinčanom 13','1 Janez 4'],verse:'1 Kor 13,13',quote:'Zdaj pa ostanejo vera, upanje, ljubezen, to troje. In največja od teh je ljubezen.',summary:'Svetopisemska ljubezen ni le čustvo, ampak zavestna drža, ki išče dobro drugega in izvira iz Boga.',context:'Pavel govori skupnosti, kjer so darovi in znanje postali razlog za primerjanje. Janez pa pokaže, da je resnična ljubezen dokaz, da človek pozna Boga.',links:['3 Mojzesova 19,18','Janez 13,34–35','Rimljanom 5,8'],today:'Ljubezen se danes pokaže v potrpežljivosti, resnici, odpuščanju in dejanjih, ki ne iščejo lastne koristi.',questions:['Komu danes najtežje izkazujem potrpežljivo ljubezen?','Ali moja dejanja potrjujejo besede, ki jih govorim?','Kje me Bog kliče, da naredim prvi korak?']},
{id:'faith',name:'Vera',keywords:['vera','zaupanje','preizkušnja'],chapters:['Hebrejcem 11','Jakob 1'],verse:'Heb 11,1',quote:'Vera pa je obstoj resničnosti, v katere upamo, zagotovilo stvari, ki jih ne vidimo.',summary:'Vera je zaupanje v Boga, ki postane vidno v poslušnosti, vztrajnosti in dejanjih.',context:'Hebrejcem povzema pričevanja ljudi, ki so živeli iz vere. Jakob razlaga, da preizkušnje razkrijejo in utrdijo pristno vero.',links:['1 Mojzesova 12','Habakuk 2,4','Rimljanom 4'],today:'Vera se ne meri samo po občutku gotovosti, ampak po tem, komu zaupamo, ko izida še ne vidimo.',questions:['Kaj trenutno izročam Bogu samo z besedami, ne pa tudi z dejanji?','Katera pretekla Božja zvestoba me danes krepi?','Kateri korak poslušnosti je pred menoj?']},
{id:'hope',name:'Upanje',keywords:['upanje','žalost','prihodnost'],chapters:['Psalm 42','Rimljanom 8'],verse:'Rim 8,24–25',quote:'Če pa upamo to, česar ne vidimo, pričakujemo to s potrpežljivostjo.',summary:'Svetopisemsko upanje ne zanika bolečine, ampak se nasloni na Božjo navzočnost in prihodnjo obnovo.',context:'Psalmist se pogovarja s svojo potrto dušo. Pavel pa trpljenje umesti v širšo zgodbo stvarstva, ki pričakuje odrešenje.',links:['Žalostinke 3,21–24','Izaija 40,31','Razodetje 21,1–5'],today:'Ko čustva govorijo, da ni izhoda, vera spomni dušo na Boga, ki še ni dokončal svojega dela.',questions:['Kaj danes najbolj obremenjuje mojo dušo?','Katere Božje obljube moram znova izgovoriti samemu sebi?','Kako lahko nekomu drugemu prinesem upanje?']},
{id:'peace',name:'Mir',keywords:['mir','nemir','strah','skrb'],chapters:['Janez 14','Filipljanom 4'],verse:'Flp 4,6–7',quote:'In Božji mir, ki presega vsak um, bo varoval vaša srca in vaše misli v Kristusu Jezusu.',summary:'Božji mir ni odsotnost težav, ampak Božja navzočnost sredi njih.',context:'Jezus učence pripravlja na preizkušnjo, Pavel pa vernike vabi, naj skrbi spreminjajo v molitev in hvaležnost.',links:['Psalm 23','Izaija 26,3','Janez 16,33'],today:'Mir raste, ko svoje skrbi poimenujemo, jih izročimo Bogu in ostanemo v njegovi besedi.',questions:['Katera skrb mi danes jemlje mir?','Kaj lahko konkretno izročim Bogu?','Kako lahko ustvarim prostor za tišino in molitev?']},
{id:'forgiveness',name:'Odpuščanje',keywords:['odpuščanje','milost','sprava','krivda'],chapters:['Matej 18','Filemonu 1'],verse:'Kol 3,13',quote:'Kakor je Gospod odpustil vam, tako tudi vi odpuščajte.',summary:'Odpuščanje ni zanikanje krivice, ampak odpoved osebnemu maščevanju zaradi milosti, ki smo jo sami prejeli.',context:'Jezus z zgodbo o neusmiljenem služabniku razkrije protislovje med prejeto in zavrnjeno milostjo.',links:['1 Mojzesova 50,17–21','Luka 23,34','Kološanom 3,13'],today:'Odpuščanje je pogosto proces. Lahko vključuje meje, resnico in posledice, vendar srce izroči sodbo Bogu.',questions:['Komu še vedno dolgujem odpuščanje?','Ali zamenjujem odpuščanje z odobravanjem dejanja?','Kaj pomeni danes izročiti sodbo Bogu?']}
];
export const paths=[
{id:'jesus-ot',title:'Jezus skozi Staro zavezo',desc:'Obljube, podobe in prerokbe, ki kažejo na Kristusa.',days:['1 Mojzesova 3,15','1 Mojzesova 22','2 Mojzesova 12','4 Mojzesova 21','Psalm 22','Izaija 7','Izaija 9','Izaija 53','Mihej 5','Zaharija 9']},
{id:'faith-trials',title:'Vera v preizkušnjah',desc:'Kako ostati zvest, ko odgovorov še ni.',days:['Jakob 1','1 Peter 1','Psalm 13','Job 1','Daniel 3','Habakuk 3','Rimljanom 5']},
{id:'promises',title:'Božje obljube',desc:'Poglobljeno branje obljub od Geneze do Razodetja.',days:['1 Mojzesova 12','2 Mojzesova 6','Jozue 1','Psalm 23','Izaija 40','Jeremija 31','Janez 14','Rimljanom 8','Razodetje 21']},
{id:'holy-spirit',title:'Sveti Duh',desc:'Njegovo delovanje, sad in moč za pričevanje.',days:['Ezekiel 36','Joel 3','Janez 14','Janez 16','Apostolska dela 2','Rimljanom 8','Galačanom 5']}
];