export const topics=[
 {id:'love',name:'Ljubezen',keywords:['ljubezen','odpuščanje','služenje'],chapters:['1 Korinčanom 13','1 Janez 4'],verse:'1 Kor 13,13',summary:'Svetopisemska ljubezen ni le čustvo, ampak zavestna drža, ki išče dobro drugega in izvira iz Boga.',context:'Pavel govori skupnosti, kjer so darovi in znanje postali razlog za primerjanje. Janez pa pokaže, da je resnična ljubezen dokaz, da človek pozna Boga.',links:['3 Mojzesova 19,18','Janez 13,34–35','Rimljanom 5,8'],today:'Ljubezen se danes pokaže v potrpežljivosti, resnici, odpuščanju in dejanjih, ki ne iščejo lastne koristi.',questions:['Komu danes najtežje izkazujem potrpežljivo ljubezen?','Ali moja dejanja potrjujejo besede, ki jih govorim?','Kje me Bog kliče, da naredim prvi korak?']},
 {id:'faith',name:'Vera',keywords:['vera','zaupanje','preizkušnja'],chapters:['Hebrejcem 11','Jakob 1'],verse:'Heb 11,1',summary:'Vera je zaupanje v Boga, ki postane vidno v poslušnosti, vztrajnosti in dejanjih.',context:'Hebrejcem povzema pričevanja ljudi, ki so živeli iz vere. Jakob razlaga, da preizkušnje razkrijejo in utrdijo pristno vero.',links:['1 Mojzesova 12','Habakuk 2,4','Rimljanom 4'],today:'Vera se ne meri samo po občutku gotovosti, ampak po tem, komu zaupamo, ko izida še ne vidimo.',questions:['Kaj trenutno izročam Bogu samo z besedami, ne pa tudi z dejanji?','Katera pretekla Božja zvestoba me danes krepi?','Kateri korak poslušnosti je pred menoj?']},
 {id:'hope',name:'Upanje',keywords:['upanje','žalost','prihodnost'],chapters:['Psalm 42','Rimljanom 8'],verse:'Rim 8,24–25',summary:'Svetopisemsko upanje ne zanika bolečine, ampak se nasloni na Božjo navzočnost in prihodnjo obnovo.',context:'Psalmist se pogovarja s svojo potrto dušo. Pavel pa trpljenje umesti v širšo zgodbo stvarstva, ki pričakuje odrešenje.',links:['Žalostinke 3,21–24','Izaija 40,31','Razodetje 21,1–5'],today:'Ko čustva govorijo, da ni izhoda, vera spomni dušo na Boga, ki še ni dokončal svojega dela.',questions:['Kaj danes najbolj obremenjuje mojo dušo?','Katere Božje obljube moram znova izgovoriti samemu sebi?','Kako lahko nekomu drugemu prinesem upanje?']},
 {id:'joy',name:'Veselje',keywords:['veselje','radost','hvaležnost'],chapters:['Filipljanom 4','Psalm 16'],verse:'Flp 4,4',summary:'Krščansko veselje ni odvisno le od ugodnih okoliščin, ampak od bližine Gospoda.',context:'Pavel piše iz ujetništva, vendar govori o veselju, miru in zadovoljstvu. Psalm 16 pokaže veselje kot sad varnosti v Bogu.',links:['Nehemija 8,10','Janez 15,11','1 Tesaloničanom 5,16–18'],today:'Veselje raste, ko pozornost prestavimo z nadzora nad okoliščinami na Božjo navzočnost in zvestobo.',questions:['Kaj mi trenutno krade veselje?','Za katere tri stvari sem danes hvaležen?','Kako lahko veselje postane moja odločitev poslušnosti?']},
 {id:'grief',name:'Žalost',keywords:['žalost','tolažba','izguba'],chapters:['Psalm 13','Janez 11'],verse:'Jn 11,35',summary:'Sveto pismo žalosti ne potiska stran. Bog posluša iskren krik in v Jezusu stopi v človeške solze.',context:'Psalm 13 je molitev človeka, ki se počuti pozabljenega. Janez 11 pokaže Jezusa, ki joče, nato pa razodene svojo oblast nad smrtjo.',links:['Psalm 34,19','Izaija 53,3–4','2 Korinčanom 1,3–4'],today:'Žalost in vera se ne izključujeta. Pred Bogom smemo biti resnični, hkrati pa se držimo njegove navzočnosti.',questions:['Kaj moram danes iskreno povedati Bogu?','Ali si dovolim žalovati brez občutka krivde?','Komu lahko ponudim tiho navzočnost in tolažbo?']},
 {id:'forgiveness',name:'Odpuščanje',keywords:['odpuščanje','milost','sprava'],chapters:['Matej 18','Filemonu 1'],verse:'Mt 18,21–22',summary:'Odpuščanje ni zanikanje krivice, ampak odpoved osebnemu maščevanju zaradi milosti, ki smo jo sami prejeli.',context:'Jezus z zgodbo o neusmiljenem služabniku razkrije protislovje med prejeto in zavrnjeno milostjo. Pavel Filemona vabi v novo, bratsko razmerje z Onezimom.',links:['1 Mojzesova 50,17–21','Luka 23,34','Kološanom 3,13'],today:'Odpuščanje je pogosto proces. Lahko vključuje meje, resnico in posledice, vendar srce izroči sodbo Bogu.',questions:['Komu še vedno dolgujem odpuščanje?','Ali zamenjujem odpuščanje z odobravanjem dejanja?','Kaj pomeni danes izročiti sodbo Bogu?']}
];
export const paths=[
 {title:'Jezus skozi Staro zavezo',days:30,desc:'Obljube, podobe in prerokbe, ki kažejo na Kristusa.'},
 {title:'Vera v preizkušnjah',days:14,desc:'Kako ostati zvest, ko odgovorov še ni.'},
 {title:'Božje obljube',days:21,desc:'Poglobljeno branje obljub od Geneze do Razodetja.'},
 {title:'Sveti Duh',days:10,desc:'Njegovo delovanje, sad in moč za pričevanje.'},
 {title:'Mesijanske prerokbe',days:15,desc:'Prerokba, izpolnitev in pomen za nas danes.'}
];
